### ISSUE TITLE
[CI Error] `select` should dont break down with the selection of nothing

### ISSUE THREAD

**Issue by claudiopro** [claudiopro/learn-sass#30]
```
> workshopper-adventure-test



  Exercises should be 
    ✓ more than 0 (550ms)
    ✓ unique (449ms)
    ✓ with an empty last-line (476ms)

  `version` should
    ✓ be equal to the package.json (436ms)
    ✓ work via -v (429ms)
    ✓ work via --version (424ms)
    ✓ work via v (438ms)

  `current` should
    ✓ work with none selected but show an error (440ms)
    ✓ should store a selection (935ms)
    ✓ be reset on reset (1447ms)

  `select` should
    ✓ allow the selection of the first entry as number (2375ms)
    ✓ allow the selection of the last entry as number (1133ms)
    ✓ allow the selection of the first entry as text (1146ms)
    ✓ allow the selection of the last entry as text (1080ms)
    ✓ allow the selection of text and be okay with spaces before, after (1032ms)
    1) dont break down with the selection of nothing
    ✓ allow spaces (1023ms)


  16 passing (15s)
  1 failing

  1) `select` should dont break down with the selection of nothing:

      Uncaught AssertionError: 255 == 1
      + expected - actual

      -255
      +1
      
      at /learn-sass/node_modules/workshopper-adventure-test/spec/state.js:119:11
      at ChildProcess.exithandler (child_process.js:210:5)
      at emitTwo (events.js:87:13)
      at ChildProcess.emit (events.js:172:7)
      at maybeClose (internal/child_process.js:818:16)
      at Socket.<anonymous> (internal/child_process.js:319:11)
      at emitOne (events.js:77:13)
      at Socket.emit (events.js:169:7)
      at Pipe._onclose (net.js:469:12)
```

**Comment by claudiopro** [comment]
@martinheidegger any idea on this one? I can't find anything similar on `learnyounode` issues. See also the [Travis build](https://travis-ci.org/claudiopro/learn-sass/jobs/89191427).

**Comment by claudiopro** [comment]
Nevermind, I see `learnyounode` fails on the same test.

**Comment by martinheidegger** [comment]
Bug on workshopper-adventure, could be detected earlier if https://github.com/workshopper/workshopper-adventure/issues/19 would run `workshopper-adventure-test` against the `example`

**Comment by claudiopro** [comment]
@martinheidegger thanks!
